name: generate animation

on:
  # run automatically every Monday
  schedule:
    - cron: "0 0 * * 1" 
  
  # allows to manually run the job at any time
  workflow_dispatch:


jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: checkout master
        uses: actions/checkout@v3
        
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            images/github-contribution-grid-snake.svg
            images/github-contribution-grid-snake-dark.svg?palette=github-dark
      
      - name: Get Hot Repos
        id: get-repos
        uses: zachary-cauchi/github-action-hot-repos@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          mdFilepath: hot-repos.md
          mdHeader: '## My latest repo activity'

      - name: Append new changes to readme.
        run: |
          search_text='![](replace-with-hot-repos)'
          value=$(<hot-repos.md)
          echo "Adding hot-repos.md to README.md"

          echo "Replacing '$search_text' in README.md"
          sed -i 's/$search_text/$value/' README.md

      - uses: EndBug/add-and-commit@v9
        with:
          add: '[images, README.md]'
          default_author: github_actions
          message: 'feat: update snake svgs and readme'

      # - name: commit svgs to master
      #   run: |
      #     git config user.name github-actions
      #     git config user.email github-actions@github.com
      #     git add images
      #     git commit -m "feat: updated snake animation svgs"
      #     git push
