name: Produce Hot Repos List

on:
  push:

  # allows to manually run the job at any time
  workflow_dispatch:


jobs:
  hot-repos:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: checkout master
        uses: actions/checkout@v3
